### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by davin67** [layer5io/.github#11]
**Current State:**

**Desired State:**

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Hi @davin67, thanks for opening up this issue. Are there any additional details that you'd like to add?
