### ISSUE TITLE
Help Wanted badges showing "0" open issues

### ISSUE THREAD

**Issue by leecalcote** [layer5io/.github#14]
#### Description
The [Help Wanted badges](https://github.com/layer5io/.github/blob/master/profile/README.md) are showing "0" open issues, but should be showing a specific count.

#### Screenshots/Logs

<img width="333" alt="Screen Shot 2022-05-27 at 4 11 13 PM" src="https://user-images.githubusercontent.com/7570704/170790091-a6bdca87-5533-479d-b713-df28a69019c2.png">

**Comment by kingebere** [comment]
is this still open?

**Comment by leecalcote** [comment]
Yes, it is. Thanks for looking into this, @kingebere
