### ISSUE TITLE
[README] Dark mode support: Add light versions of logos 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/.github#17]
#### Current Behavior
This repo's readme.md (https://github.com/layer5io/.github/blob/master/profile/README.md) assumes light mode visitors.

**Desired Situation**
Use GitHub's relatively new ability to define [light and dark mode images](More context - https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/) in markdown for each of the logos.

Find light and dark mode flavors of each of the logos here: https://layer5.io/brand or in the shared, community drive.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by poly4concept** [comment]
I would love to work on this pls assign it to me

**Comment by SaNsK11** [comment]
I would like to work on it. Can you assign it to me @leecalcote

**Comment by leecalcote** [comment]
Oops... I missed, @poly4concept's earlier message. I'm assigning to both of you assuming that @poly4concept has moved on...
