### ISSUE TITLE
[Markdown] Enhance footer with social icons

### ISSUE THREAD

**Issue by leecalcote** [layer5io/.github#2]
#### Current Behavior
The bottom of the [readme](https://github.com/layer5io) could be more interesting.

#### Desired Behavior
Enhance footer with social icons similar to that of the footer on layer5.io

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by toth2000** [comment]
Can I work on this issue?.

**Comment by warunicorn19** [comment]
Sure @toth2000.

**Comment by warunicorn19** [comment]
@debo19 assign.
