### ISSUE TITLE
Layer5 Community Welcome Guide is not present on the given Location !! (In profile/README.md)

### ISSUE THREAD

**Issue by BaibhavTiwari** [layer5io/.github#21]
**Current State:**
The Current state of [Layer5 Community Welcome Guide](https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit) is that  it has been deleted from the google drive.

**Desired State:**
The guide should be present there.

**Image:**
![image](https://user-images.githubusercontent.com/75496387/213845189-b32dfa30-c47a-48ea-96f2-934a8336407c.png)

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by UtkarshMishra12** [comment]
Please replace the current link with this one https://layer5.io/community/handbook/repository-overview

**Comment by BaibhavTiwari** [comment]
okk !! sure
