### ISSUE TITLE
Add entry for MeshMap project

### ISSUE THREAD

**Issue by leecalcote** [layer5io/.github#24]
#### Current Behavior
https://layer5.io/meshmap project is missing from the project list on the [`layer5io` org profile](https://github.com/layer5io/.github/blob/master/profile/README.md).

#### Implementation
use the MeshMap logo from layer5.io/brand and create new entry with a short description

---
#### Contributor [Handbook](https://layer5.io/community/handbook)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Younus-Saberi** [comment]
Hello @leecalcote, I am interested to contribute to this issue, can you please assign it to me so that I can start to work on

**Comment by leecalcote** [comment]
Sounds great, @Younus-Saberi

**Comment by Younus-Saberi** [comment]
Thank you @leecalcote 😄, I have made a PR regarding it. Do let me know your suggestion
