### ISSUE TITLE
[Docs] query parameter mismatch in profile/readme.md file

### ISSUE THREAD

**Issue by akshay-bharadva** [layer5io/.github#27]
File : [profile/README.md](https://github.com/layer5io/.github/blob/master/profile/README.md?plain=1#L38) for label `help wanted`

**Current State:**
```
<a href="https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+org%3Alayer5labs+label%3A%22help+wanted%22+" alt="Help wanted across orgs">
```
**Desired State:**
```
<a href="https://github.com/search?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+org%3Alayer5labs+label%3A%22help+wanted%22" alt="Help wanted across orgs">
```
---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Layak-Ali** [comment]
> s

whats the use of this? There is no need for any changes

**Comment by akshay-bharadva** [comment]
@Layak-Ali Thank you, At the time when I created this issue, I didn't get any results on the given URL so I checked with the URL and thought the actual path was `/search` not `/issues`, but now it's working. Thank you for taking a look into it, I'm closing the issue.

**Comment by Layak-Ali** [comment]
@akshay-bharadva Yes. I tried to work on this issue but found no error so i informed you.
