### ISSUE TITLE
[Docs] Update the README.md of Layer5io to show new X logo (formerly Twitter)

### ISSUE THREAD

**Issue by Layak-Ali** [layer5io/.github#28]
**Current State:**
There are 5 icons that are still using the old version of the 'X' logo( Formerly Twitter). 

**Desired State:**
Please find them in the 'Profile > README.md' section and change all occurrences of the Twitter logo to the new 'X' logo. Make sure you follow the theme.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Viveksati5143** [comment]
Hi @l5io Can i work on this issue as this is stale?

**Comment by Layak-Ali** [comment]
@l5io you can assign him this issue. I am busy with other issues currently.

**Comment by Viveksati5143** [comment]
> @l5io you can assign him this issue. I am busy with other issues currently.

Thanks for the confirmation

**Comment by Viveksati5143** [comment]
Hey @Layak-Ali 
Where can I find all the 5 twitter logos?...as I can only see 2 bird logo here: 
https://github.com/layer5io/.github/tree/master/profile

**Comment by Layak-Ali** [comment]
@Viveksati5143 you should ask this question on slack general channel of Layer5.

**Comment by captain-Akshay** [comment]
@abhijeetgauravm can i work on this ?

**Comment by Viveksati5143** [comment]
> @abhijeetgauravm can i work on this ?

Hi Akshay, there is no matching X logo available in the repo. So, I'm currently requesting it and working on it

**Comment by ritiksaxena124** [comment]
> > @abhijeetgauravm can i work on this ?
> 
> Hi Akshay, there is no matching X logo available in the repo. So, I'm currently requesting it and working on it

Here is a new twitter logo that you can use
![Twitter Logo](https://github.com/layer5io/.github/assets/51539117/b15ecccf-8ee5-439f-9458-7a7608636b29)

**Comment by abhijeetgauravm** [comment]
> > > @abhijeetgauravm can i work on this ?
> > 
> > 
> > Hi Akshay, there is no matching X logo available in the repo. So, I'm currently requesting it and working on it
> 
> Here is a new twitter logo that you can use ![Twitter Logo](https://user-images.githubusercontent.com/51539117/272993747-b15ecccf-8ee5-439f-9458-7a7608636b29.svg)

// @Viveksati5143

**Comment by Viveksati5143** [comment]
> > > @abhijeetgauravm can i work on this ?
> > 
> > 
> > Hi Akshay, there is no matching X logo available in the repo. So, I'm currently requesting it and working on it
> 
> Here is a new twitter logo that you can use ![Twitter Logo](https://user-images.githubusercontent.com/51539117/272993747-b15ecccf-8ee5-439f-9458-7a7608636b29.svg)

I added the fill attribute with the same color & now it looks something like [this](https://github.com/Viveksati5143/.github/blob/twitter/assets/social-icons/x.svg):

BUt still it still it has some problem showing up: [here](https://github.com/Viveksati5143/.github/tree/twitter/profile)

**Comment by Viveksati5143** [comment]
> > > > @abhijeetgauravm can i work on this ?
> > > 
> > > 
> > > Hi Akshay, there is no matching X logo available in the repo. So, I'm currently requesting it and working on it
> > 
> > 
> > Here is a new twitter logo that you can use ![Twitter Logo](https://user-images.githubusercontent.com/51539117/272993747-b15ecccf-8ee5-439f-9458-7a7608636b29.svg)
> 
> // @Viveksati5143

And I can't understand why my post is flagged...now I can't reply there!!!??

**Comment by abhijeetgauravm** [comment]
> > > > > @abhijeetgauravm can i work on this ?
> > > > 
> > > > 
> > > > Hi Akshay, there is no matching X logo available in the repo. So, I'm currently requesting it and working on it
> > > 
> > > 
> > > Here is a new twitter logo that you can use ![Twitter Logo](https://user-images.githubusercontent.com/51539117/272993747-b15ecccf-8ee5-439f-9458-7a7608636b29.svg)
> > 
> > 
> > // @Viveksati5143
> 
> And I can't understand why my post is flagged...now I can't reply there!!!??

// @saurabh100ni

**Comment by Viveksati5143** [comment]
@abhijeetgauravm can you add hacktoberfest label to it?

**Comment by leecalcote** [comment]
No need. The repo has the hacktoberfest topic.

**Comment by leecalcote** [comment]
Thanks for this issue, @Layak-Ali! 👍
