### ISSUE TITLE
[BUG] Youtube link of Layer5 is broken

### ISSUE THREAD

**Issue by Viveksati5143** [layer5io/.github#29]
#### Description

YouTube link of Layer5 is broken in the readme of Layer5

#### Expected Behavior
It should redirect to official youtube channel of Layer5

#### Screenshots/Logs

<img width="960" alt="image" src="https://github.com/layer5io/.github/assets/100852245/d56ebf10-1cdd-49be-a89b-f935bd92cc37">

#### Environment:
- Meshery Version: 
- Kubernetes Version: 
- Host OS: Windows
- Browser: Microsoft Edge

#### To Reproduce
1. Go to 'https://github.com/layer5io'
2. Click on 'Subscribers'
3. See error

**Comment by Viveksati5143** [comment]
Hi @l5io👋
Can I work on this issue as my first issue in this community?
Thanks

**Comment by vishalvivekm** [comment]
Hi @Viveksati5143 
Thanks for pointing it out. Yeah please go ahead and replace the link with : https://www.youtube.com/channel/UCFL1af7_wdnhHXL1InzaMvA?sub_confirmation=1

**Comment by Viveksati5143** [comment]
> Hi @Viveksati5143 Thanks for pointing it out. Yeah please go ahead and replace the link with : https://www.youtube.com/channel/UCFL1af7_wdnhHXL1InzaMvA?sub_confirmation=1

Thanks @vishalvivekm Can you please guide me where to contribute?
