### ISSUE TITLE
[Markdown] Update hyperlinks to point to contributor stats.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/.github#3]
#### Current Behavior

<img width="900" alt="Screen Shot 2021-09-21 at 8 44 49 AM" src="https://user-images.githubusercontent.com/7570704/134182142-7726a026-000e-4752-81d9-9dd1bea0c6ce.png">

#### Desired Behavior
Update the hyperlink for each contributor badge to point to the <org>/<repo>/graphs/contributors

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by monalisha31** [comment]
Can i work on this issue?

**Comment by debo19** [comment]
Go ahead @monalisha31
