### ISSUE TITLE
[Docs] Broken links of Layer5 Community Welcome Guide

### ISSUE THREAD

**Issue by Viveksati5143** [layer5io/.github#30]
**Current State:**
The Current state of [Layer5 Community Welcome Guide](https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit) is that it has been deleted from the google drive.

**Desired State:**
Both the links should be updated with the new link of the guide.

Screenshots:
<img width="960" alt="image" src="https://github.com/layer5io/.github/assets/100852245/de524466-8364-44eb-895f-a9de05691237">
![image](https://github.com/layer5io/.github/assets/100852245/474c0a6c-33c9-46a5-ac72-53c09d00b76d)

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Viveksati5143** [comment]
Hi @l5io👋
I would like to work on this issue.
Thanks

**Comment by vishalvivekm** [comment]
Thanks @Viveksati5143

The link should point to https://layer5.io/community/newcomers
