### ISSUE TITLE
[Markdown] Add shield for count of open "help wanted" issues under each project

### ISSUE THREAD

**Issue by leecalcote** [layer5io/.github#4]
#### Current Behavior
Missing "help wanted" shield with count of open issues.

<img width="895" alt="Screen Shot 2021-09-21 at 8 46 24 AM" src="https://user-images.githubusercontent.com/7570704/134182479-5780ef22-81c8-486d-bb6e-a473d031187a.png">

#### Desired Behavior
Include the “help wanted” for each of these orgs or maybe those could be on the individual projects.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by sudhay23** [comment]
Hello @leecalcote. Can I work on this? And can you please brief me about getting started?

**Comment by sudhay23** [comment]
Does this help?
![GitHub issues by-label](https://img.shields.io/github/issues/layer5io/.github/help%20wanted.svg)

**Comment by san-coding** [comment]
yes @sudhay23 , let the text be just `help wanted`, like this
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/65719940/134210548-33687f9e-9ddb-464e-8904-525cdb267b6b.png">

**Comment by san-coding** [comment]
Sorry, what you have done is correct

**Comment by debo19** [comment]
@sudhay23 Use advanced queries on https://shields.io (example: https://img.shields.io/github/contributors/layer5io/layer5.svg) for each project individually .

**Comment by sudhay23** [comment]
@debo19 Is it okay to add 4 individual shields in this repo's README each one pointing to `help-wanted` issues of each project?

**Comment by sudhay23** [comment]
@debo19 Is this way to organize the shield desired?
![image](https://user-images.githubusercontent.com/59689805/134297631-ba110978-a14c-41e5-b923-bd86a3e2d2d3.png)

**Comment by debo19** [comment]
@sudhay23 you have to add it to the Projects section for this one (refer to the screenshot in the issue) and please try to make all shields appear horizontally

**Comment by sudhay23** [comment]
@debo19 Sure. I'll put them in the right place. And can you clarify **horizontally** a bit more? I thought of placing the shields in the line right after the last sentence of description about each project

**Comment by debo19** [comment]
@sudhay23 I meant if you're adding more than one shield like in the picture you shared...they should be side by side and not  in a column format. You can go ahead with placing them after the description, do share a screenshot after you do , it'll be easier to check how it's looking🚀

**Comment by sudhay23** [comment]
@debo19 Yeah sure. 👍

**Comment by sudhay23** [comment]
Meshery => `https://github.com/meshery/meshery/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+org%3Ameshery`

This is the repo i could find for Meshery. But I'm unable to spot the right repo to source information from for the other projects. Can you please help me out with the appropriate repo URLs @debo19 ?

**Comment by sudhay23** [comment]
@debo19 @leecalcote Can you please verify the screenshot?

![image](https://user-images.githubusercontent.com/59689805/134317830-6df594ac-8982-4ab0-95a6-324d10b3f4cb.png)

**Comment by debo19** [comment]
@sudhay23 looks good

**Comment by sudhay23** [comment]
@debo19 Thanks. I'll open my PR now
