### ISSUE TITLE
[Markdown] Add Service Mesh Patterns to project list

### ISSUE THREAD

**Issue by leecalcote** [layer5io/.github#5]
#### Current Behavior
The https://github.com/service-mesh-patterns project is missing from the project list.

<img width="895" alt="Screen Shot 2021-09-21 at 8 46 24 AM" src="https://user-images.githubusercontent.com/7570704/134182671-03261c05-ecb8-4e6a-a057-984d7c1519ff.png">

#### Desired Behavior
Include this project alongside the others.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Shivanshu97i** [comment]
Hi @leecalcote can I work on this issue ?

**Comment by warunicorn19** [comment]
Sure @Shivanshu97i

**Comment by warunicorn19** [comment]
@debo19 if you could please assign.

**Comment by Shivanshu97i** [comment]
Thanks, will start immediately and looking forward to future contributions
